### ISSUE TITLE
Input Resolution Influence on mAP

### ISSUE THREAD

**Issue by skywalker9096** [xw-hu/SINet#4]
hello @xw-hu , I followed you instructions and trained the model myself and get good performance(mAP on Car: 89.63), but when I use smaller input size on the same model, the mAP drops to 79.40/56.42. any idea what happens? I am rather confused.

model | resolution | Car | Ped | Cyc | FPS
-- | -- | -- | -- | -- | --
mscnn | 1280x384 | 75.43 | 78.95 | 77.04 | 11
mscnn | 2560x756 | 91.38 | - | - | 3
SINet | 1920x576 | 89.63 | 72.26 | 61.72 | 21
SINet | 1280x384 | 79.40 | 65.37 | 44.47 | 37
SINet-Car | 864x256 | 56.42 | - | - | 59

I use 3712 images for training and 3769 images for validation.

**Comment by xw-hu** [comment]
I guess you forgot to adjust some parameters (such as the size of anchor, the parameters of ROISplit Layer). Since the original parameters are calculated for Car detection, that is why the accuracy of Ped and Cyc is not as good as Car. You may re-calculate these parameters, and I also provide the matlab files on parameter calculation for your reference.
